"""
Phase 5 - create the Texas healthcare demand campaign and push its leads.

Creates the campaign as DRAFT with NO sending accounts. Jude attaches mailboxes
and activates in the UI (standing rule).

Sequence is modelled on "HR - May 8", Jude's best-performing campaign
(4.00% reply): fast cadence 2/1/1/1, follow-ups two to three lines, no
apologising, no restating the offer. Step 1 carries {{personalization}}
(the body generated by generate_texas_demand.py, which deliberately has NO
sign-off) and the sequence appends "Best,{{sendingAccountFirstName}}".

  BEFORE ACTIVATING: the nexamai.info mailboxes have first_name set to the
  full string "Rood Judeley", so {{sendingAccountFirstName}} renders
  "Best, Rood Judeley" while the body says "My name is Rood". Split the
  account name fields to Rood / Judeley first.

Custom variables MUST go in "custom_variables" -- Instantly merges that into
the stored payload. Nesting under "payload" is silently replaced and loose
top-level keys are dropped. Verify with a fresh GET, not the write response.

Guards: duplicate emails (in-run + any row already AA=TRUE), AA=BLOCKLISTED
never retried, blocklist 400s marked permanently, AA written every 10 pushes.

Run:
  python3 -W ignore push_texas_demand.py --sheet_url "URL" --dry_run
  python3 -W ignore push_texas_demand.py --sheet_url "URL"
  python3 -W ignore push_texas_demand.py --sheet_url "URL" --campaign_id ID
"""

import os
import re
import time
import argparse
import requests
from urllib.parse import urlparse

from dotenv import load_dotenv
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(SCRIPT_DIR, "..", "..", "..", ".env"))
TOKEN_PATH = os.path.join(SCRIPT_DIR, "..", "..", "..", "token.json")

INSTANTLY_KEY = os.getenv("INSTANTLY_API_KEY")
BASE = "https://api.instantly.ai/api/v2"
BATCH = 10

SUBJECT = "Sanity checking timing"

# 0-based cols, Outreach tab. AD (29) = Keep Reason, never touched.
C_JOBID, C_TITLE, C_COMPANY, C_WEBSITE = 0, 1, 10, 11
C_CITY, C_STATE = 17, 18
C_DM_TITLE, C_EMAIL, C_FIRST, C_LAST = 20, 22, 23, 24
C_BODY, C_ADDED, C_STATUS = 25, 26, 27
C_CROLE, C_RPLUR, C_ETYPE, C_CFIRST, C_CCITY = 30, 31, 32, 33, 34

SIGN_IPAD = ("<br /><br />Best,<br />{{sendingAccountFirstName}}"
             "<br /><br />Sent from my iPad")
SIGN_IPHONE = ("<br /><br />Best,<br />{{sendingAccountFirstName}}"
               "<br /><br />Sent from my iPhone")

STEP1 = "<div>{{personalization}}" + SIGN_IPAD + "</div>"
STEP2 = ("<div>Hi {{firstName}},<br /><br />"
         "Just bumping this.<br />"
         "Is the {{cleaned_role}} role still open?" + SIGN_IPHONE + "</div>")
STEP3 = ("<div>Hi {{firstName}},<br /><br />"
         "Quick one, still hiring or has it been parked?<br /><br />"
         "Happy to make the intro if you are still looking." + SIGN_IPAD + "</div>")
STEP4 = ("<div>Hi {{firstName}},<br /><br />"
         "Going to close this out. If it opens back up, reach out and I'll "
         "make the intro." + SIGN_IPHONE + "</div>")


def headers():
    return {"Authorization": f"Bearer {INSTANTLY_KEY}",
            "Content-Type": "application/json"}


def root_domain(host):
    host = (host or "").lower().strip()
    if not host:
        return ""
    if host.startswith("http"):
        host = urlparse(host).netloc
    host = host[4:] if host.startswith("www.") else host
    parts = host.split(".")
    return ".".join(parts[-2:]) if len(parts) >= 2 else host


def create_campaign(name):
    step = lambda d, subj, body: {
        "type": "email", "delay": d, "delay_unit": "days",
        "pre_delay_unit": "days",
        "variants": [{"subject": subj, "body": body}]}
    payload = {
        "name": name,
        "campaign_schedule": {"schedules": [{
            "name": "Default",
            "timing": {"from": "07:00", "to": "18:00"},
            "days": {"1": True, "2": True, "3": True, "4": True, "5": True},
            "timezone": "America/Chicago",          # Texas
        }]},
        "sequences": [{"steps": [
            step(2, SUBJECT, STEP1),
            step(1, "", STEP2),
            step(1, "", STEP3),
            step(1, "", STEP4),
        ]}],
        "daily_limit": 500,
        "stop_on_reply": True,
        "stop_on_auto_reply": False,
        "link_tracking": False,
        "open_tracking": False,
        "text_only": True,
        "first_email_text_only": True,
        "prioritize_new_leads": False,
        "stop_for_company": False,
    }
    resp = requests.post(f"{BASE}/campaigns", headers=headers(),
                         json=payload, timeout=30)
    if resp.status_code != 200:
        print(f"campaign creation error {resp.status_code}: {resp.text[:500]}")
        resp.raise_for_status()
    return resp.json()["id"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sheet_url", required=True)
    ap.add_argument("--tab", default="Outreach")
    ap.add_argument("--campaign_name", default="Texas Healthcare Demand - Jul 22")
    ap.add_argument("--campaign_id", default="", help="resume into existing campaign")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--hold_domain_mismatch", action="store_true",
                    help="skip rows where email domain != website domain "
                         "(most are legit corporate-parent domains, so OFF by default)")
    ap.add_argument("--dry_run", action="store_true")
    args = ap.parse_args()
    TAB = args.tab

    sheet_id = re.search(r"/spreadsheets/d/([a-zA-Z0-9_-]+)", args.sheet_url).group(1)
    creds = Credentials.from_authorized_user_file(TOKEN_PATH)
    svc = build("sheets", "v4", credentials=creds)
    rows = svc.spreadsheets().values().get(
        spreadsheetId=sheet_id, range=f"'{TAB}'!A1:AJ").execute().get("values", [])
    data = rows[1:]

    def cell(r, i):
        return r[i].strip() if i < len(r) and r[i] else ""

    seen = {cell(r, C_EMAIL).lower() for r in data
            if cell(r, C_ADDED).upper() == "TRUE" and cell(r, C_EMAIL)}

    todo, dupes, mismatch = [], 0, []
    for i, r in enumerate(data):
        if args.limit and len(todo) >= args.limit:
            break
        if not cell(r, C_STATUS).startswith("found"):
            continue
        # HELD = manually excluded (e.g. website-builder / freemail addresses
        # that are not the employer's own domain). Never auto-retried.
        if cell(r, C_ADDED).upper() in ("TRUE", "BLOCKLISTED", "HELD"):
            continue
        email, body = cell(r, C_EMAIL), cell(r, C_BODY)
        if not email or not body:
            continue
        if email.lower() in seen:
            dupes += 1
            continue
        wd = root_domain(cell(r, C_WEBSITE))
        ed = root_domain(email.split("@")[-1])
        if wd and ed and wd != ed:
            mismatch.append((i + 2, cell(r, C_COMPANY), email, wd))
            if args.hold_domain_mismatch:
                continue
        seen.add(email.lower())
        todo.append((i + 2, r))

    print(f"tab={TAB}")
    print(f"to push : {len(todo)}")
    print(f"dupes   : {dupes}")
    print(f"domain mismatches: {len(mismatch)} "
          f"({'HELD' if args.hold_domain_mismatch else 'pushed anyway'})")
    for row_n, comp, em, wd in mismatch[:10]:
        print(f"    row {row_n}: {comp} | {em} | site {wd}")
    if args.dry_run:
        print("\n--- DRY RUN, nothing created or pushed ---")
        print(f"would create campaign: {args.campaign_name!r}")
        return

    cid = args.campaign_id or create_campaign(args.campaign_name)
    if not args.campaign_id:
        print(f"\ncreated DRAFT campaign {cid} ({args.campaign_name!r})")
        print("  no sending accounts attached - Jude adds them in the UI")

    pushed, blocked, failed = 0, 0, []
    pending = []

    def flush():
        nonlocal pending
        if pending:
            svc.spreadsheets().values().batchUpdate(
                spreadsheetId=sheet_id,
                body={"valueInputOption": "RAW", "data": pending}).execute()
            pending = []

    for n, (row_n, r) in enumerate(todo, 1):
        job_id = cell(r, C_JOBID)
        payload = {
            "campaign": cid,
            "email": cell(r, C_EMAIL),
            "first_name": cell(r, C_CFIRST) or cell(r, C_FIRST),
            "last_name": cell(r, C_LAST),
            "company_name": cell(r, C_COMPANY),
            "website": cell(r, C_WEBSITE),
            "personalization": cell(r, C_BODY),
            "custom_variables": {
                "cleaned_role": cell(r, C_CROLE),
                "role_plural": cell(r, C_RPLUR),
                "employer_type": cell(r, C_ETYPE),
                "city": cell(r, C_CCITY) or cell(r, C_CITY),
                "job_title": cell(r, C_TITLE),
                "dm_title": cell(r, C_DM_TITLE),
                "company_website": cell(r, C_WEBSITE),
                "job_post_url": (f"https://www.indeed.com/viewjob?jk={job_id}"
                                 if job_id else ""),
            },
        }
        try:
            resp = requests.post(f"{BASE}/leads", headers=headers(),
                                 json=payload, timeout=30)
        except requests.RequestException as e:
            failed.append((row_n, str(e)[:80]))
            continue
        if resp.status_code == 200:
            pending.append({"range": f"'{TAB}'!AA{row_n}", "values": [["TRUE"]]})
            pushed += 1
        elif resp.status_code == 400 and "blocklist" in resp.text.lower():
            pending.append({"range": f"'{TAB}'!AA{row_n}",
                            "values": [["BLOCKLISTED"]]})
            blocked += 1
        else:
            failed.append((row_n, f"{resp.status_code}: {resp.text[:80]}"))
        if n % BATCH == 0:
            flush()
            print(f"  -- {n}/{len(todo)} | pushed {pushed} | "
                  f"blocklisted {blocked} | failed {len(failed)}")
        time.sleep(0.15)
    flush()

    print("\n=== Summary ===")
    print(f"  Campaign:     {cid}  (DRAFT)")
    print(f"  Pushed:       {pushed}")
    print(f"  Blocklisted:  {blocked}")
    print(f"  Dupes:        {dupes}")
    print(f"  Failed:       {len(failed)}")
    for f in failed[:10]:
        print("   ", f)


if __name__ == "__main__":
    main()
