"""
Phase 5 — push the commercial-pool connector campaign to Instantly as a DRAFT.

Approved package (Jude, 2026-08-04):
  Step 1 (subject per variant, via {{subject_line}} custom var):
    'practice staffing'      -> Variant A rows (new practices)
    'new location staffing'  -> Variant B/C rows (expansions, multi-site)
    body = {{personalization}} (col Z, generated by generate_connector_emails.py)
  Step 2, day 2, BLANK subject:
    quick one. Staffing sorted for {{city}}, or still building the team?
  Step 3, day 5 (3 days later), BLANK subject:
    Leaving the door open. When hiring comes up, I'm one reply away.

Rules honored: campaign stays DRAFT (Jude activates in the UI), text_only +
first_email_text_only, NO sending accounts, one lead per unique inbox
(first row wins, siblings marked DUP), custom vars sent as top-level
custom_variables and verified with a fresh GET, blocklist rejections marked
BLOCKLISTED and never retried, batch-of-10 sheet marks, resume-safe.

Usage:
  python3 -W ignore .claude/skills/nppes-new-clinics/scripts/push_connector_campaign.py \
      --sheet_url URL [--campaign_id ID] [--limit N] [--dry_run]
"""
import argparse
import json
import os
import sys
import time
from collections import defaultdict

import requests
from dotenv import load_dotenv

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
load_dotenv(os.path.join(SCRIPT_DIR, "..", "..", "..", ".env"))

from generate_connector_emails import (get_service, site_key, casual_city,
                                       C_STATUS_LEAD, C_COMPANY, C_CITY,
                                       C_EMAIL, C_FIRST, C_BODY)

INSTANTLY_BASE = "https://api.instantly.ai/api/v2"
TAB = "Leads"
C_LAST, C_ADDED = 24, 26
CAMPAIGN_NAME = "New Clinics Connector - Aug 2026"

# Signature lives in the SEQUENCE (renders per sending account), never in the
# per-lead personalization body (Jude, 2026-08-04).
SIG = "<br><br>Best,<br>{{sendingAccountFirstName}}<br><br>Sent from my iPhone"
STEP1 = "<div>{{personalization}}" + SIG + "</div>"
FU1 = ("<div>quick one. Staffing sorted for {{city}}, or still building the team?"
       + SIG + "</div>")
FU2 = ("<div>Leaving the door open. When hiring comes up, I'm one reply away."
       + SIG + "</div>")


def headers():
    return {"Authorization": f"Bearer {os.getenv('INSTANTLY_API_KEY')}",
            "Content-Type": "application/json"}


def create_campaign():
    payload = {
        "name": CAMPAIGN_NAME,
        "campaign_schedule": {"schedules": [{
            "name": "New schedule",
            "timing": {"from": "09:00", "to": "18:00"},
            "days": {"1": True, "2": True, "3": True, "4": True, "5": True},
            "timezone": "America/Chicago",
        }]},
        "sequences": [{"steps": [
            {"type": "email", "delay": 2, "delay_unit": "days", "pre_delay_unit": "days",
             "variants": [{"subject": "Sanity check", "body": STEP1}]},
            {"type": "email", "delay": 2, "delay_unit": "days", "pre_delay_unit": "days",
             "variants": [{"subject": "", "body": FU1}]},
            {"type": "email", "delay": 3, "delay_unit": "days", "pre_delay_unit": "days",
             "variants": [{"subject": "", "body": FU2}]},
        ]}],
        "daily_limit": 500,
        "stop_on_reply": True,
        "stop_on_auto_reply": False,
        "link_tracking": False,
        "open_tracking": False,
        "text_only": True,
        "first_email_text_only": True,
        "prioritize_new_leads": False,
        "stop_for_company": False,
    }
    r = requests.post(f"{INSTANTLY_BASE}/campaigns", headers=headers(),
                      json=payload, timeout=30)
    if r.status_code != 200:
        print(f"campaign create failed {r.status_code}: {r.text[:400]}")
        r.raise_for_status()
    return r.json()["id"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sheet_url", required=True)
    ap.add_argument("--campaign_id", default="", help="reuse an existing campaign")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--dry_run", action="store_true")
    args = ap.parse_args()

    svc = get_service()
    sid = args.sheet_url.split("/d/")[1].split("/")[0]
    values = svc.spreadsheets().values().get(
        spreadsheetId=sid, range=f"'{TAB}'!A2:AI").execute().get("values", [])

    def c(r, i):
        return r[i].strip() if len(r) > i and r[i] else ""

    groups = defaultdict(list)          # email -> [(row_num, row)]
    for n, r in enumerate(values, start=2):
        em = c(r, C_EMAIL).lower()
        if em and c(r, C_BODY):
            groups[em].append((n, r))

    leads, dup_marks = [], []
    for em, rows in groups.items():
        rows.sort()
        if any(c(r, C_ADDED).upper() in ("TRUE", "BLOCKLISTED") for _, r in rows):
            continue                     # resume-safe: inbox already handled
        n0, r0 = rows[0]
        dup_marks += [(n, "DUP") for n, _ in rows[1:] if not c(_, C_ADDED)]
        sites = {site_key(r) for _, r in rows}
        cities = sorted({casual_city(c(r, C_CITY)) for _, r in rows if c(r, C_CITY)})
        is_multi = len(sites) > 1
        subject = ("practice staffing"
                   if not is_multi and c(r0, C_STATUS_LEAD).startswith("NEW PRACTICE")
                   else "new location staffing")
        city_var = cities[0] if (not is_multi or len(cities) == 1) else "the new sites"
        # personalization is a RESERVED first-class lead field — inside
        # custom_variables Instantly silently stores it as "" and the
        # sequence preview renders blank (burned 2026-08-04). Top level only.
        leads.append((n0, {
            "email": em,
            "first_name": c(r0, C_FIRST).title() if c(r0, C_FIRST).isupper() else c(r0, C_FIRST),
            "last_name": c(r0, C_LAST).title() if c(r0, C_LAST).isupper() else c(r0, C_LAST),
            "company_name": c(r0, C_COMPANY),
            "personalization": c(r0, C_BODY),
            "custom_variables": {
                "subject_line": subject,
                "city": city_var,
            },
        }))
    if args.limit:
        leads = leads[:args.limit]
    n_a = sum(1 for _, l in leads if l["custom_variables"]["subject_line"] == "practice staffing")
    print(f"[push] {len(leads)} unique leads ({n_a} practice staffing / "
          f"{len(leads)-n_a} new location staffing) | {len(dup_marks)} dup rows"
          f"{' | DRY RUN' if args.dry_run else ''}")
    if args.dry_run:
        for _, l in leads[:5]:
            print(f"  {l['email']:44s} {l['custom_variables']['subject_line']:22s} "
                  f"city={l['custom_variables']['city']}")
        return

    cid = args.campaign_id or create_campaign()
    print(f"[push] campaign {cid} (DRAFT — not activated)")

    marks, pushed, blocked = list(dup_marks), 0, 0
    for i, (n0, lead) in enumerate(leads):
        lead["campaign"] = cid
        try:
            r = requests.post(f"{INSTANTLY_BASE}/leads", headers=headers(),
                              json=lead, timeout=30)
            ok, text = r.status_code == 200, r.text[:300]
        except requests.exceptions.RequestException as e:
            ok, text = False, str(e)
        if ok:
            pushed += 1
            marks.append((n0, "TRUE"))
            if pushed == 1:              # verify custom vars persisted (standing rule)
                lid = r.json().get("id")
                g = requests.get(f"{INSTANTLY_BASE}/leads/{lid}", headers=headers(),
                                 timeout=30).json()
                cv = g.get("payload", {}) or {}
                have = all(k in json.dumps(g) for k in
                           ("personalization", "subject_line", "city"))
                print(f"  custom-var persistence check on {lead['email']}: "
                      f"{'OK' if have else 'MISSING — STOPPING'}")
                if not have:
                    sys.exit(1)
        elif "block" in (text or "").lower():
            blocked += 1
            marks.append((n0, "BLOCKLISTED"))
        else:
            print(f"  FAIL {lead['email']}: {text}")
        if len(marks) >= 10:             # batch-of-10
            svc.spreadsheets().values().batchUpdate(
                spreadsheetId=sid, body={"valueInputOption": "RAW", "data": [
                    {"range": f"'{TAB}'!AA{rn}", "values": [[v]]} for rn, v in marks
                ]}).execute()
            marks = []
        if (i + 1) % 25 == 0:
            print(f"  {i+1}/{len(leads)} | pushed {pushed} | blocklisted {blocked}",
                  flush=True)
        time.sleep(0.3)
    if marks:
        svc.spreadsheets().values().batchUpdate(
            spreadsheetId=sid, body={"valueInputOption": "RAW", "data": [
                {"range": f"'{TAB}'!AA{rn}", "values": [[v]]} for rn, v in marks
            ]}).execute()
    print(f"\n[push] done: {pushed} pushed, {blocked} blocklisted, campaign {cid} "
          f"is DRAFT — review and activate in Instantly")


if __name__ == "__main__":
    main()
